### ISSUE TITLE
A lot of toppings don't work

### ISSUE THREAD

**Issue by DaMatrix** [mcdevs/Burger#26]
Trying to run Burger on a 1.12.2 jar, and am getting errors on the majority of toppings.

[Full log](https://pastebin.com/HKKDNg1H)

Per-topping breakdown of functionality (check mark means it works):
- [x] biomes
- [ ] blocks
- [ ] blockstates
- [ ] entities
- [x] identify
- [ ] items
- [x] language
- [ ] objects
- [x] packetinstructions
- [x] packets
- [ ] recipes
- [x] sounds
- [x] stats
- [x] tags (output is completely empty for this though, is that intended?)
- [x] tileentities
- [x] version

I'm running `Python 3.6.7`, and the latest commit from `master` (3fb06528d8f3fd10dd505b9d81d333156061b61e).

Am I doing something wrong, is the latest commit for 1.13 only (I haven't even tried it on 1.13 yet), or are these toppings just fundamentally broken?

**Comment by Pokechu22** [comment]
Hm, that's odd.  1.12.2 _should_ work fine on master along with 1.13; I'm currently working on 1.14 on [my fork, branch 1.14-dev](https://github.com/pokechu22/burger/tree/1.14-dev).  I'll do some testing...

Note that many toppings depend on other toppings; in particular the `objects` topping depends on `entities` (and it looks like only `entities` is failing) and the `items`, `blockstates`, and `recipes` toppings depend on `blocks` (which also seems to be failing).  `tags` being empty is to be expected for 1.12 since [tags](https://minecraft.gamepedia.com/Tag) were only added in 1.13.

**Comment by DaMatrix** [comment]
Well I've also tried running it with all toppings enabled, and get the same error on `entities`, so that's definitely a thing. Should I try going back a few commits (and if so, which one should I try)?

**Comment by Pokechu22** [comment]
It works on my machine&trade; so that's odd.

One thing I see is that it's in `_entities_1point10` for the entities topping, which shouldn't be the case (it should be using the 1.11 format).  Can you give me the output of the `versions` topping?

One other thing I forgot about: on my 1.14-dev branch I've changed it so that if one topping fails to run, it'll continue running the other toppings that don't depend on it (instead of just dying in the middle).  I probably should cherry-pick that change (and maybe the download JAR changes too) into a separate branch and merge that into master since they're not directly 1.14 things and would help with stuff like this.

**Comment by Pokechu22** [comment]
Alright, that did have a difference: when I run it I get

```json
        "version": {
            "data": 1343,
            "entity_format": "1.11",
            "is_flattened": false,
            "name": "1.12.2",
            "protocol": 340
        }
```

but you're missing the data version and thus the entity format is wrong:

```json
        "version": {
            "entity_format": "1.10",
            "is_flattened": false,
            "name": "1.12.2",
            "protocol": 340
        }
```

I'm not sure why that's the case.  The only thing I know is different about my setup is that I'm testing with Python 3.6.4 on cygwin and also python 3.6.5 on my raspberry pi and it works for both there.  I'll try 3.6.7 and see if that makes a difference...


-----

The download thing not working is why I have changes to merge, see Pokechu22/Burger#10.  It's been broken for ages.

**Comment by Pokechu22** [comment]
I _can_ reproduce it with 3.6.7 on WSL.  I'm not sure if that's because I have something else different on WSL or what exactly, but at least I can reproduce it.

**Comment by DaMatrix** [comment]
nope, it doesn't happen on that commit.

**Comment by Pokechu22** [comment]
Alright, the issue is I started depending on a newer jawa feature, but it's not in a version published on PyPI yet.  My guess is I built it off of master locally on both machines but not on WSL, so WSL was using the PyPI version.  I'll ask tktech to release a new version, but in the mean time using the older commit or installing jawa locally would both work.

**Comment by DaMatrix** [comment]
Alright, thanks for your time and quick responses! I'll probably just go for the old version for now.
